inherits:
  - utils:base-all

strictness: none
member-warnings: true

pylint:
  enabled:
    - useless-suppression
    # By default disabled by Prospector
    - no-member
    - no-name-in-module
  disable:
    # Prefer: TD003(ruff): Missing issue link for this TODO
    - fixme # TODO fix for matrix_identifier = resolution
    - unused-import # Use the Ruff version instead: F401
    - undefined-variable # Use the Ruff version instead: F821
    - unused-variable # Use the Ruff version instead: F841
    - indentation-mixture # Use the Ruff version instead: D206
    - misplaced-future # Use the Ruff version instead: F404
    - bad-indentation # Use the Ruff version instead: D207, D208
    - undefined-all-variable # Use the Ruff version instead: F822
    - duplicate-argument-name # Use the Ruff version instead: F831
    - function-redefined # Use the Ruff version instead: F811
    - f-string-without-interpolation # Use the Ruff version instead: F541
    - duplicate-key # Use the Ruff version instead: F601
    - too-many-star-expressions # Use the Ruff version instead: F622
    - assert-on-tuple # Use the Ruff version instead: F631
    - not-in-loop # Use the Ruff version instead: F701, F702
    - yield-outside-function # Use the Ruff version instead: F704
    - return-outside-function # Use the Ruff version instead: F706
    - bad-except-order # Use the Ruff version instead: F707
    - notimplemented-raised # Use the Ruff version instead: F901
    - bad-classmethod-argument # Use the Ruff version instead: N804
    - redefined-outer-name # Use the Ruff version instead: F810
    - wildcard-import # Use the Ruff version instead: F403
    - bare-except # Use the Ruff version instead: E722, S110, S112
    - broad-exception-caught # Use the Ruff version instead: BLE001
    - broad-except # Use the Ruff version instead: BLE001
    - broad-exception-raised # Use the Ruff version instead: TRY002
    - invalid-name # Use the Ruff version instead: N802, N803, N806
    - missing-docstring # Use the Ruff version instead: D100, D101, D102, D103
    - unused-argument # Use the Ruff version instead: ARG001
    - protected-access # Use the Ruff version instead: SLF001
    - missing-timeout # Use the Ruff version instead: S113
    - raise-missing-from # Use the Ruff version instead: B904
    - eval-used # Use the Ruff version instead: S307
    - consider-using-with # Use the Ruff version instead: SIM115
    - logging-fstring-interpolation # Use the Ruff version instead: G004
    - continue-in-finally # Use the Ruff version instead: F703, PLE0116
    - too-many-branches # Use the Ruff version instead: PLR0912
    - too-many-statements # Use the Ruff version instead: PLR0915
    - subprocess-run-check # Use the Ruff version instead: S603, PLW1510
    - import-outside-toplevel # Use the Ruff version instead: PLC0415
    - type-name-incorrect-variance # Use the Ruff version instead: PLC0105
    - type-bivariance # Use the Ruff version instead: PLC0131
    - type-param-name-mismatch # Use the Ruff version instead: PLC0132
    - single-string-slots # Use the Ruff version instead: PLC0205
    - dict-index-missing-items # Use the Ruff version instead: PLC0206
    - iteration-over-set # Use the Ruff version instead: PLC0208
    - useless-import-alias # Use the Ruff version instead: PLC0414
    - import-outside-top-level # Use the Ruff version instead: PLC0415
    - len-test # Use the Ruff version instead: PLC1802
    - compare-to-empty-string # Use the Ruff version instead: PLC1901
    - non-ascii-name # Use the Ruff version instead: PLC2401
    - non-ascii-import-name # Use the Ruff version instead: PLC2403
    - import-private-name # Use the Ruff version instead: PLC2701
    - unnecessary-dunder-call # Use the Ruff version instead: PLC2801
    - unnecessary-direct-lambda-call # Use the Ruff version instead: PLC3002
    - yield-in-init # Use the Ruff version instead: PLE0100
    - return-in-init # Use the Ruff version instead: PLE0101
    - nonlocal-and-global # Use the Ruff version instead: PLE0115
    - nonlocal-without-binding # Use the Ruff version instead: PLE0117
    - load-before-global-declaration # Use the Ruff version instead: PLE0118
    - non-slot-assignment # Use the Ruff version instead: PLE0237
    - duplicate-bases # Use the Ruff version instead: PLE0241
    - unexpected-special-method-signature # Use the Ruff version instead: PLE0302
    - invalid-length-return-type # Use the Ruff version instead: PLE0303
    - invalid-bool-return-type # Use the Ruff version instead: PLE0304
    - invalid-index-return-type # Use the Ruff version instead: PLE0305
    - invalid-str-return-type # Use the Ruff version instead: PLE0307
    - invalid-bytes-return-type # Use the Ruff version instead: PLE0308
    - invalid-hash-return-type # Use the Ruff version instead: PLE0309
    - invalid-all-object # Use the Ruff version instead: PLE0604
    - invalid-all-format # Use the Ruff version instead: PLE0605
    - potential-index-error # Use the Ruff version instead: PLE0643
    - misplaced-bare-raise # Use the Ruff version instead: PLE0704
    - repeated-keyword-argument # Use the Ruff version instead: PLE1132
    - dict-iter-missing-items # Use the Ruff version instead: PLE1141
    - await-outside-async # Use the Ruff version instead: PLE1142
    - logging-too-many-args # Use the Ruff version instead: PLE1205
    - logging-too-few-args # Use the Ruff version instead: PLE1206
    - bad-string-format-character # Use the Ruff version instead: PLE1300
    - bad-string-format-type # Use the Ruff version instead: PLE1307
    - bad-str-strip-call # Use the Ruff version instead: PLE1310
    - invalid-envvar-value # Use the Ruff version instead: PLE1507
    - singledispatch-method # Use the Ruff version instead: PLE1519
    - singledispatchmethod-function # Use the Ruff version instead: PLE1520
    - yield-from-in-async-function # Use the Ruff version instead: PLE1700
    - bidirectional-unicode # Use the Ruff version instead: PLE2502
    - invalid-character-backspace # Use the Ruff version instead: PLE2510
    - invalid-character-sub # Use the Ruff version instead: PLE2512
    - invalid-character-esc # Use the Ruff version instead: PLE2513
    - invalid-character-nul # Use the Ruff version instead: PLE2514
    - invalid-character-zero-width-space # Use the Ruff version instead: PLE2515
    - comparison-with-itself # Use the Ruff version instead: PLR0124
    - comparison-of-constant # Use the Ruff version instead: PLR0133
    - no-classmethod-decorator # Use the Ruff version instead: PLR0202
    - no-staticmethod-decorator # Use the Ruff version instead: PLR0203
    - property-with-parameters # Use the Ruff version instead: PLR0206
    - manual-from-import # Use the Ruff version instead: PLR0402
    - too-many-public-methods # Use the Ruff version instead: PLR0904
    - too-many-return-statements # Use the Ruff version instead: PLR0911
    - too-many-arguments # Use the Ruff version instead: PLR0913
    - too-many-locals # Use the Ruff version instead: PLR0914
    - too-many-boolean-expressions # Use the Ruff version instead: PLR0916
    - too-many-positional-arguments # Use the Ruff version instead: PLR0917
    - repeated-isinstance-calls # Use the Ruff version instead: PLR1701
    - too-many-nested-blocks # Use the Ruff version instead: PLR1702
    - redefined-argument-from-local # Use the Ruff version instead: PLR1704
    - and-or-ternary # Use the Ruff version instead: PLR1706
    - useless-return # Use the Ruff version instead: PLR1711
    - repeated-equality-comparison # Use the Ruff version instead: PLR1714
    - boolean-chained-comparison # Use the Ruff version instead: PLR1716
    - sys-exit-alias # Use the Ruff version instead: PLR1722
    - if-stmt-min-max # Use the Ruff version instead: PLR1730
    - unnecessary-dict-index-lookup # Use the Ruff version instead: PLR1733
    - unnecessary-list-index-lookup # Use the Ruff version instead: PLR1736
    - magic-value-comparison # Use the Ruff version instead: PLR2004
    - empty-comment # Use the Ruff version instead: PLR2044
    - collapsible-else-if # Use the Ruff version instead: PLR5501
    - non-augmented-assignment # Use the Ruff version instead: PLR6104
    - literal-membership # Use the Ruff version instead: PLR6201
    - no-self-use # Use the Ruff version instead: PLR6301
    - unnecessary-lambda # Use the Ruff version instead: PLW0108
    - useless-else-on-loop # Use the Ruff version instead: PLW0120
    - self-assigning-variable # Use the Ruff version instead: PLW0127
    - redeclared-assigned-name # Use the Ruff version instead: PLW0128
    - assert-on-string-literal # Use the Ruff version instead: PLW0129
    - named-expr-without-context # Use the Ruff version instead: PLW0131
    - useless-exception-statement # Use the Ruff version instead: PLW0133
    - nan-comparison # Use the Ruff version instead: PLW0177
    - bad-staticmethod-argument # Use the Ruff version instead: PLW0211
    - redefined-slots-in-subclass # Use the Ruff version instead: PLW0244
    - super-without-brackets # Use the Ruff version instead: PLW0245
    - import-self # Use the Ruff version instead: PLW0406
    - global-variable-not-assigned # Use the Ruff version instead: PLW0602
    - global-statement # Use the Ruff version instead: PLW0603
    - global-at-module-level # Use the Ruff version instead: PLW0604
    - self-or-cls-assignment # Use the Ruff version instead: PLW0642
    - binary-op-exception # Use the Ruff version instead: PLW0711
    - bad-open-mode # Use the Ruff version instead: PLW1501
    - shallow-copy-environ # Use the Ruff version instead: PLW1507
    - invalid-envvar-default # Use the Ruff version instead: PLW1508
    - subprocess-popen-preexec-fn # Use the Ruff version instead: PLW1509
    - subprocess-run-without-check # Use the Ruff version instead: PLW1510
    - unspecified-encoding # Use the Ruff version instead: PLW1514
    - eq-without-hash # Use the Ruff version instead: PLW1641
    - useless-with-lock # Use the Ruff version instead: PLW2101
    - redefined-loop-name # Use the Ruff version instead: PLW2901
    - bad-dunder-method-name # Use the Ruff version instead: PLW3201
    - nested-min-max # Use the Ruff version instead: PLW3301

mypy:
  run: true
  options:
    python-version: '3.9'
    ignore-missing-imports: true
    warn-redundant-casts: true
    warn-unused-ignores: true
    strict: true

bandit:
  run: true
  disable:
    - B101 # Use of assert detected.
    - B404 # Consider possible security implications associated with the subprocess module.

pyroma:
  run: true

ruff:
  options:
    extend-select:
      ALL: true

  disable:
    - FA # Function annotations
    - D100 # Missing docstring in public module
    - D104 # Missing docstring in public package
    - D105 # Missing docstring in magic method
    - D107 # Missing docstring in __init__
    - E501 # Line too long (should be done by formatter, length not configurable in prospector)
    # Multi-line docstring summary should start at the first line [See: https://docs.astral.sh/ruff/rules/multi-line-summary-first-line,
    # Incompatible with pydocstyle D213 Multi-line docstring summary should start at the second line.
    - D212
    - FBT001 # Boolean-typed positional argument in function definition
    - FBT002 # Boolean default positional argument in function definition
    - T201 # `print` found
    - ANN401 # Dynamically typed expressions (typing.Any) are disallowed
    - EM101 # Exception must not use a string literal, assign to variable first
    - EM102 # Exception must not use an f-string literal, assign to variable first
    - TD002 # Missing author in TODO
    # Annoying rule
    - ERA001 # Found commented-out code)
    # No more active on Python version >= 3.11
    - PERF203 # try-except-in-loop
    # Prefer: TD003(ruff): Missing issue link for this TODO
    - FIX002 # Line contains TODO, consider resolving the issue

pydocstyle:
  disable:
    - D105 # Missing docstring in magic method
    - D107 # Missing docstring in __init__
