inherits:
  - utils:base-all

strictness: none
member-warnings: true

pylint:
  enabled:
    - useless-suppression
    # By default disabled by Prospector
    - no-member
    - no-name-in-module

mypy:
  run: true
  options:
    python-version: '3.9'
    ignore-missing-imports: true
    warn-redundant-casts: true
    warn-unused-ignores: true
    strict: true

bandit:
  run: true
  disable:
    - B101 # Use of assert detected.
    - B404 # Consider possible security implications associated with the subprocess module.

pyroma:
  run: true

ruff:
  options:
    extend-select:
      F: true # Pyflakes
      E: true # pycodestyle
      W: true # pycodestyle
      N: true # pep8-naming
      D: true # pydocstyle
      YTT: true # flake8-2020
      ANN: true # flake8-annotations
      ASYNC: true # flake8-async
      A: true # flake8-builtins
      C4: true # flake8-comprehensions
      DTZ: true # flake8-datetimez
      LOG: true # flake8-logging
      G: true # flake8-logging-format
      PIE: true # flake8-pie
      PYI: true # flake8-pyi
      PT: true # flake8-pytest-style
      RET: true # flake8-return
      SIM: true # flake8-simplify
      TC: true # flake8-type-checking
      INT: true # flake8-gettext
      PTH: true # flake8-use-pathlib
      ERA: true # eradicate
      PD: true # pandas-vet
      PGH: true # pygrep-hooks
      PL: true # Pylint
      TRY: true # tryceratops
      NPY: true # NumPy-specific rules
      FAST: true # FastAPI
      AIR: true # Airflow
      PERF: true # Perflint
      FURB: true # refurb
      DOC: true # pydoclint
      RUF: true # Ruff-specific rules

  disable:
    - D100 # Missing docstring in public module
    - D104 # Missing docstring in public package
    - D105 # Missing docstring in magic method
    - D107 # Missing docstring in __init__
    - E501 # Line too long (should be done by formatter, length not configurable in prospector)
    # Multi-line docstring summary should start at the first line [See: https://docs.astral.sh/ruff/rules/multi-line-summary-first-line,
    # Fix applicability: safe]
    # Incompatible with pydocstyle D213 Multi-line docstring summary should start at the second line.
    - D212

pydocstyle:
  disable:
    - D105 # Missing docstring in magic method
    - D107 # Missing docstring in __init__
