strictness: veryhigh

max-line-length: 110

pylint:
  enabled:
    - useless-suppression

mypy:
  run: true
  options:
    python-version: '3.9'
    ignore-missing-imports: true
    warn-redundant-casts: true
    warn-unused-ignores: true
    strict: true

bandit:
  run: true
  disable:
    - B101 # Use of assert detected.

pyroma:
  run: true

ruff:
  run: true
  options:
    extend-select:
      E: true # Pycodestyle
      F: true # Pyflakes
      UP: true # pyupgrade
      B: true # flake8-bugbear
      SIM: true # flake8-simplify
      I: true # isort
      S: true # flake8-bandit
      D: true # pydocstyle
    fix: true
  disable:
    - S101 # Use of assert detected
    - SIM105 # suppressible-exception (slow code)
    - D100 # Missing docstring in public module
    - D104 # Missing docstring in public package
    - D105 # Missing docstring in magic method
    - E501 # Line too long (should be done by formatter, length not configurable in prospector)

mccabe:
  run: false
