strictness: veryhigh

max-line-length: 110

pylint:
  enabled:
    - useless-suppression

mypy:
  run: true
  options:
    python-version: '3.9'
    ignore-missing-imports: true
    strict: true

bandit:
  run: true

pyroma:
  run: true

mccabe:
  run: false
